# Official Federated LSTM

Ovaj notebook je sluzbeni execution path za federirano ucenje LSTM modela nad EV charging forecasting splitovima.
Zadrzava isti `LSTMRegressor`, istu evaluacijsku logiku i isti artifact stil kao centralized LSTM notebook, ali trenira globalni model kroz FedAvg ili FedProx.

## Sto se ovdje dogada

Notebook prolazi kroz cijeli federirani workflow:

1. Ucitava federirane `.npz` splitove po klijentima.
2. Validira da svaki split ima oblik `[N, 24, 19]` i da nema NaN/Inf vrijednosti.
3. Trenera lokalne LSTM modele na privatnom `train.npz` splitu svakog klijenta.
4. Agregira lokalne tezine ponderiranim FedAvg pravilom.
5. Evaluira globalni model na spojenim train/val/test splitovima bez mijesanja splitova.
6. Sprema metrike, checkpoint, predikcije i osnovne grafove.

## 1. Configuration

Parametri za brzi debug run su na jednom mjestu. Za puni eksperiment povecaj `NUM_ROUNDS` i postavi `DEBUG_MAX_CLIENTS = None`.

In [19]:
ALGORITHM = "fedavg"  # "fedavg" or "fedprox"
SCENARIO = "iid"  # "iid" or "non_iid"

NUM_ROUNDS = 100
LOCAL_EPOCHS = 3
BATCH_SIZE = 256
LR = 0.001
WEIGHT_DECAY = 0.0
GRAD_CLIP_NORM = 1.0
FEDPROX_MU = 0.01
SEED = 42

HIDDEN_SIZE = 128
NUM_LAYERS = 1
DROPOUT = 0.0
DEVICE_REQUEST = "auto"

# None means auto-detect from SCENARIO. You can set an explicit path string here.
FEDERATED_DATASET_DIR = None
OUTPUT_ROOT = None
RUN_NAME = None

# Initial debug default: use only first 5 clients. Set to None for all clients.
DEBUG_MAX_CLIENTS = None

## 2. Imports and paths

Prvo nalazimo project root, dodajemo ga u `sys.path`, pa importamo postojece projektne module.

In [20]:
import json
import os
import random
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.nn.utils import clip_grad_norm_
from torch.utils.data import DataLoader, TensorDataset

CURRENT_DIR = Path.cwd().resolve()
if (CURRENT_DIR / "diplomski").exists():
    PROJECT_ROOT = CURRENT_DIR
elif (CURRENT_DIR.parent / "diplomski").exists():
    PROJECT_ROOT = CURRENT_DIR.parent
else:
    fallback_root = Path("/home/azureuser/cloudfiles/code/Users/lgjuric/federated-ev-charging-forecasting").resolve()
    if not (fallback_root / "diplomski").exists():
        raise RuntimeError("Run this notebook from the project root or from notebooks/.")
    PROJECT_ROOT = fallback_root

os.chdir(PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from diplomski.evaluation import (
    SUPPORTED_FEATURE_COUNT,
    SUPPORTED_HORIZON,
    SUPPORTED_TARGET_COLUMN,
    SUPPORTED_WINDOW_SIZE,
    build_prediction_frame,
    compute_regression_metrics,
    configure_run_logger,
    load_experiment_metadata,
    make_run_name,
    validate_official_task,
)
from diplomski.models import LSTMRegressor
from diplomski.preprocessing.utils import save_json

try:
    from diplomski.evaluation import evaluate_split as project_evaluate_split
except ImportError:
    project_evaluate_split = None

ALGORITHM = ALGORITHM.strip().lower()
SCENARIO = SCENARIO.strip().lower()
if ALGORITHM not in {"fedavg", "fedprox"}:
    raise ValueError("ALGORITHM must be 'fedavg' or 'fedprox'.")
if SCENARIO not in {"iid", "non_iid"}:
    raise ValueError("SCENARIO must be 'iid' or 'non_iid'.")

METADATA_PATH = Path(
    os.environ.get(
        "DIPLOMSKI_EXPERIMENT_METADATA",
        str(PROJECT_ROOT / "data" / "processed" / "experiments" / "artifacts" / "experiment_metadata.json"),
    )
).resolve()

if FEDERATED_DATASET_DIR is None:
    env_dataset_dir = os.environ.get("DIPLOMSKI_FL_DATASET_DIR")
    FEDERATED_DATASET_DIR = Path(env_dataset_dir).resolve() if env_dataset_dir else None
else:
    FEDERATED_DATASET_DIR = Path(FEDERATED_DATASET_DIR).resolve()

if OUTPUT_ROOT is None:
    OUTPUT_ROOT = Path(
        os.environ.get(
            "DIPLOMSKI_FL_OUTPUT_ROOT",
            str(PROJECT_ROOT / "data" / "processed" / "results" / "federated"),
        )
    ).resolve()
else:
    OUTPUT_ROOT = Path(OUTPUT_ROOT).resolve()

if RUN_NAME is None:
    RUN_NAME = os.environ.get("DIPLOMSKI_FL_RUN_NAME", f"notebook_{ALGORITHM}_{SCENARIO}_{make_run_name()}")

run_dir = OUTPUT_ROOT / RUN_NAME
plots_dir = run_dir / "plots"
run_dir.mkdir(parents=True, exist_ok=True)
plots_dir.mkdir(parents=True, exist_ok=True)

print(f"PROJECT_ROOT={PROJECT_ROOT}")
print(f"ALGORITHM={ALGORITHM} SCENARIO={SCENARIO}")
print(f"METADATA_PATH={METADATA_PATH}")
print(f"OUTPUT_ROOT={OUTPUT_ROOT}")
print(f"RUN_NAME={RUN_NAME}")

PROJECT_ROOT=/mnt/batch/tasks/shared/LS_root/mounts/clusters/lgjuric2/code/Users/lgjuric/federated-ev-charging-forecasting
ALGORITHM=fedavg SCENARIO=iid
METADATA_PATH=/mnt/batch/tasks/shared/LS_root/mounts/clusters/lgjuric2/code/Users/lgjuric/federated-ev-charging-forecasting/data/processed/experiments/artifacts/experiment_metadata.json
OUTPUT_ROOT=/mnt/batch/tasks/shared/LS_root/mounts/clusters/lgjuric2/code/Users/lgjuric/federated-ev-charging-forecasting/data/processed/results/federated
RUN_NAME=notebook_fedavg_iid_20260511T184320Z

## 3. Data structures

`SplitArrays` opisuje jedan `.npz` split, a `ClientDatasetBundle` drzi tri splita jednog federiranog klijenta.

In [21]:
@dataclass(frozen=True)
class SplitArrays:
    X: np.ndarray
    y: np.ndarray
    t: np.ndarray
    station_ids: np.ndarray


@dataclass(frozen=True)
class ClientDatasetBundle:
    client_id: str
    train: SplitArrays
    val: SplitArrays
    test: SplitArrays

## 4. Loading functions

Ove funkcije su namjerno stroge oko sheme i oblika podataka. Prazni splitovi su dozvoljeni, ali se preskacu kod globalne evaluacije.

In [22]:
def resolve_federated_dataset_dir(project_root: Path, scenario: str, configured_dir: Path | None) -> Path:
    if configured_dir is not None:
        if not configured_dir.exists():
            raise FileNotFoundError(f"Configured FEDERATED_DATASET_DIR does not exist: {configured_dir}")
        return configured_dir

    candidates_by_scenario = {
        "iid": [
            project_root / "data" / "processed" / "experiments" / "federated" / "iid_40_clients",
            project_root / "data" / "processed" / "experiments" / "iid",
        ],
        "non_iid": [
            project_root / "data" / "processed" / "experiments" / "federated" / "non_iid_station",
            project_root / "data" / "processed" / "experiments" / "non_iid_station",
        ],
    }
    for candidate in candidates_by_scenario[scenario]:
        if candidate.exists():
            return candidate.resolve()
    searched = "\n".join(str(path) for path in candidates_by_scenario[scenario])
    raise FileNotFoundError(f"Could not find federated dataset directory. Searched:\n{searched}")


def load_split_npz(
    path: Path,
    split_name: str,
    expected_window_size: int,
    expected_feature_count: int,
) -> SplitArrays:
    if not path.exists():
        raise FileNotFoundError(f"Missing {split_name} split file: {path}")

    required_keys = {"X", "y", "t", "station_ids"}
    with np.load(path) as data:
        missing_keys = required_keys.difference(data.files)
        if missing_keys:
            raise RuntimeError(
                f"{split_name} split at {path} is missing keys {sorted(missing_keys)}. "
                f"Available keys: {sorted(data.files)}."
            )
        X = data["X"].astype(np.float32, copy=False)
        y = data["y"].astype(np.float32, copy=False)
        t = data["t"].astype(str)
        station_ids = data["station_ids"].astype(str)

    if X.ndim != 3:
        raise RuntimeError(f"{split_name} X must be 3D, got shape {X.shape} in {path}.")
    if y.ndim != 1:
        raise RuntimeError(f"{split_name} y must be 1D, got shape {y.shape} in {path}.")
    if X.shape[1] != expected_window_size:
        raise RuntimeError(
            f"{split_name} X has window size {X.shape[1]}, expected {expected_window_size} in {path}."
        )
    if X.shape[2] != expected_feature_count:
        raise RuntimeError(
            f"{split_name} X has feature count {X.shape[2]}, expected {expected_feature_count} in {path}."
        )
    if not (len(X) == len(y) == len(t) == len(station_ids)):
        raise RuntimeError(
            f"{split_name} arrays must agree on sample count in {path}: "
            f"len(X)={len(X)}, len(y)={len(y)}, len(t)={len(t)}, len(station_ids)={len(station_ids)}."
        )
    if not np.isfinite(X).all() or not np.isfinite(y).all():
        raise RuntimeError(f"{split_name} split contains NaN or Inf values: {path}")

    return SplitArrays(X=X, y=y, t=t, station_ids=station_ids)


def load_federated_clients(
    federated_dir: Path,
    expected_window_size: int,
    expected_feature_count: int,
    skip_empty_val_test: bool = False,
) -> list[ClientDatasetBundle]:
    if not federated_dir.exists():
        raise FileNotFoundError(f"Federated dataset directory not found: {federated_dir}")

    client_dirs = sorted(path for path in federated_dir.iterdir() if path.is_dir() and path.name.startswith("client_"))
    if not client_dirs:
        raise FileNotFoundError(f"No client_* directories found in {federated_dir}")

    clients: list[ClientDatasetBundle] = []
    for client_dir in client_dirs:
        splits = {
            split_name: load_split_npz(
                client_dir / f"{split_name}.npz",
                f"{client_dir.name}/{split_name}",
                expected_window_size,
                expected_feature_count,
            )
            for split_name in ("train", "val", "test")
        }
        if skip_empty_val_test and (len(splits["val"].y) == 0 or len(splits["test"].y) == 0):
            continue
        clients.append(
            ClientDatasetBundle(
                client_id=client_dir.name,
                train=splits["train"],
                val=splits["val"],
                test=splits["test"],
            )
        )

    if not clients:
        raise RuntimeError(f"No usable clients found in {federated_dir}")
    return clients


def concat_splits(clients: list[ClientDatasetBundle], split_name: str) -> SplitArrays | None:
    if split_name not in {"train", "val", "test"}:
        raise ValueError("split_name must be one of: train, val, test.")

    non_empty_splits = [getattr(client, split_name) for client in clients if len(getattr(client, split_name).y) > 0]
    if not non_empty_splits:
        return None

    return SplitArrays(
        X=np.concatenate([split.X for split in non_empty_splits], axis=0).astype(np.float32, copy=False),
        y=np.concatenate([split.y for split in non_empty_splits], axis=0).astype(np.float32, copy=False),
        t=np.concatenate([split.t for split in non_empty_splits], axis=0).astype(str),
        station_ids=np.concatenate([split.station_ids for split in non_empty_splits], axis=0).astype(str),
    )

## Shared utility functions

Ovo su male pomocne funkcije za seed, uredjaj i PyTorch DataLoader. Iste su po namjeri kao u centralized notebooku.

In [23]:
def set_global_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    if torch.backends.cudnn.is_available():
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False


def select_device(device_name: str) -> torch.device:
    normalized = device_name.strip().lower()
    if normalized == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if normalized == "cpu":
        return torch.device("cpu")
    if normalized == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA was requested but is not available.")
        return torch.device("cuda")
    raise ValueError(f"Unsupported device '{device_name}'. Use auto, cpu, or cuda.")


def build_dataloader(
    split_arrays: SplitArrays,
    batch_size: int,
    *,
    shuffle: bool,
    device: torch.device,
) -> DataLoader:
    if len(split_arrays.y) == 0:
        raise ValueError("Cannot build a DataLoader for an empty split.")
    dataset = TensorDataset(torch.from_numpy(split_arrays.X), torch.from_numpy(split_arrays.y))
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        pin_memory=device.type == "cuda",
    )


def count_trainable_parameters(model: nn.Module) -> int:
    return int(sum(parameter.numel() for parameter in model.parameters() if parameter.requires_grad))


def estimate_model_state_bytes(model: nn.Module) -> int:
    state_dict = model.state_dict()
    return int(sum(tensor.numel() * tensor.element_size() for tensor in state_dict.values()))

## 5. Data validation summary

Nakon ucitavanja klijenata spremamo tablicu s brojem uzoraka, brojem stanica u train splitu i vremenskim granicama po splitu.

In [24]:
def timestamp_bounds(values: np.ndarray) -> tuple[str | None, str | None]:
    if len(values) == 0:
        return None, None
    parsed = pd.to_datetime(pd.Series(values), errors="coerce", utc=True)
    if parsed.notna().any():
        return parsed.min().isoformat(), parsed.max().isoformat()
    as_strings = pd.Series(values).astype(str)
    return str(as_strings.min()), str(as_strings.max())


def build_client_summary(clients: list[ClientDatasetBundle]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for client in clients:
        row: dict[str, Any] = {
            "client_id": client.client_id,
            "train_samples": int(len(client.train.y)),
            "val_samples": int(len(client.val.y)),
            "test_samples": int(len(client.test.y)),
            "train_station_count": int(pd.Series(client.train.station_ids).nunique()) if len(client.train.y) else 0,
        }
        for split_name in ("train", "val", "test"):
            split_arrays = getattr(client, split_name)
            min_t, max_t = timestamp_bounds(split_arrays.t)
            row[f"{split_name}_min_t"] = min_t
            row[f"{split_name}_max_t"] = max_t
        rows.append(row)
    return pd.DataFrame(rows)


metadata = load_experiment_metadata(METADATA_PATH)
validate_official_task(metadata, expected_feature_count=SUPPORTED_FEATURE_COUNT)
EXPECTED_WINDOW_SIZE = int(metadata.get("window_size", SUPPORTED_WINDOW_SIZE))
EXPECTED_FEATURE_COUNT = int(metadata.get("feature_count", SUPPORTED_FEATURE_COUNT))
FEDERATED_DATASET_DIR = resolve_federated_dataset_dir(PROJECT_ROOT, SCENARIO, FEDERATED_DATASET_DIR)

all_clients = load_federated_clients(
    FEDERATED_DATASET_DIR,
    expected_window_size=EXPECTED_WINDOW_SIZE,
    expected_feature_count=EXPECTED_FEATURE_COUNT,
    skip_empty_val_test=(SCENARIO == "non_iid"),
)
if DEBUG_MAX_CLIENTS is not None:
    all_clients = all_clients[: int(DEBUG_MAX_CLIENTS)]

train_clients = [client for client in all_clients if len(client.train.y) > 0]
if not train_clients:
    raise RuntimeError("No clients with non-empty train splits were found.")

global_train = concat_splits(train_clients, "train")
global_val = concat_splits(all_clients, "val")
global_test = concat_splits(all_clients, "test")
if global_train is None:
    raise RuntimeError("Global train split is empty after concatenation.")
if global_val is None:
    raise RuntimeError("At least one non-empty validation split is required for model selection.")

client_summary = build_client_summary(all_clients)
client_summary.to_csv(run_dir / "client_summary.csv", index=False)

selected_device = select_device(DEVICE_REQUEST)
set_global_seed(SEED)
logger = configure_run_logger(
    name=f"diplomski.notebooks.federated_lstm.{RUN_NAME}",
    log_path=run_dir / "run.log",
)

print(f"FEDERATED_DATASET_DIR={FEDERATED_DATASET_DIR}")
print(f"selected_device={selected_device}")
print(f"loaded_clients={len(all_clients)} train_clients={len(train_clients)}")
print(
    "global samples | "
    f"train={len(global_train.y)} val={len(global_val.y)} "
    f"test={0 if global_test is None else len(global_test.y)}"
)

client_summary

FEDERATED_DATASET_DIR=/mnt/batch/tasks/shared/LS_root/mounts/clusters/lgjuric2/code/Users/lgjuric/federated-ev-charging-forecasting/data/processed/experiments/iid
selected_device=cpu
loaded_clients=40 train_clients=40
global samples | train=110642 val=6824 test=30275

,client_id,train_samples,val_samples,test_samples,train_station_count,train_min_t,train_max_t,val_min_t,val_max_t,test_min_t,test_max_t
0,client_000,2767,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-13T18:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-21T08:00:00+00:00
1,client_001,2767,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-25T07:00:00+00:00
2,client_002,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-25T02:00:00+00:00,2023-02-25T14:00:00+00:00
3,client_003,2766,171,757,40,2022-09-02T03:00:00+00:00,2023-01-05T13:00:00+00:00,2023-01-07T02:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
4,client_004,2766,171,757,40,2022-09-02T02:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T13:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
5,client_005,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-23T13:00:00+00:00,2023-02-24T01:00:00+00:00
6,client_006,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T13:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
7,client_007,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
8,client_008,2766,171,757,40,2022-09-02T01:00:00+00:00,2023-01-05T13:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
9,client_009,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-16T20:00:00+00:00,2023-02-17T08:00:00+00:00
10,client_010,2766,171,757,40,2022-09-02T01:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
11,client_011,2766,171,757,40,2022-09-02T01:00:00+00:00,2023-01-05T12:00:00+00:00,2023-01-07T07:00:00+00:00,2023-01-14T09:00:00+00:00,2023-01-28T01:00:00+00:00,2023-02-28T13:00:00+00:00
12,client_012,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
13,client_013,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T12:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
14,client_014,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-26T12:00:00+00:00,2023-02-27T00:00:00+00:00
15,client_015,2766,171,757,40,2022-09-02T02:00:00+00:00,2023-01-05T13:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
16,client_016,2766,171,757,40,2022-09-02T02:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-16T01:00:00+00:00,2023-02-28T23:00:00+00:00
17,client_017,2766,171,757,40,2022-09-02T01:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
18,client_018,2766,171,757,40,2022-09-02T01:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-07T02:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
19,client_019,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T12:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T13:00:00+00:00,2023-01-17T01:00:00+00:00,2023-02-17T13:00:00+00:00
20,client_020,2766,171,757,40,2022-09-02T01:00:00+00:00,2023-01-05T13:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
21,client_021,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
22,client_022,2766,171,757,40,2022-09-02T02:00:00+00:00,2023-01-05T12:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-23T02:00:00+00:00,2023-02-23T14:00:00+00:00
23,client_023,2766,171,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T23:00:00+00:00,2023-01-14T01:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
24,client_024,2766,170,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
25,client_025,2766,170,757,40,2022-09-02T01:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
26,client_026,2766,170,757,40,2022-09-02T00:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-16T09:00:00+00:00,2023-02-16T21:00:00+00:00
27,client_027,2766,170,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
28,client_028,2766,170,757,40,2022-09-02T01:00:00+00:00,2023-01-05T13:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
29,client_029,2766,170,757,40,2022-09-02T01:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-21T08:00:00+00:00
30,client_030,2766,170,757,40,2022-09-02T00:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
31,client_031,2766,170,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-07T09:00:00+00:00,2023-01-14T10:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
32,client_032,2766,170,757,40,2022-09-02T00:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-20T21:00:00+00:00,2023-02-21T09:00:00+00:00
33,client_033,2766,170,757,40,2022-09-02T03:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
34,client_034,2766,170,757,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-07T02:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-16T02:00:00+00:00,2023-02-28T23:00:00+00:00
35,client_035,2766,170,756,40,2022-09-02T03:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T13:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
36,client_036,2766,170,756,40,2022-09-02T00:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-19T13:00:00+00:00,2023-02-20T00:00:00+00:00
37,client_037,2766,170,756,40,2022-09-02T00:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T22:00:00+00:00,2023-01-13T23:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00
38,client_038,2766,170,756,40,2022-09-02T00:00:00+00:00,2023-01-05T14:00:00+00:00,2023-01-06T16:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-16T02:00:00+00:00,2023-02-28T23:00:00+00:00
39,client_039,2766,170,756,40,2022-09-02T00:00:00+00:00,2023-01-05T15:00:00+00:00,2023-01-07T15:00:00+00:00,2023-01-14T16:00:00+00:00,2023-01-15T17:00:00+00:00,2023-02-28T23:00:00+00:00

## Save configuration

Konfiguracija runa sprema se prije treninga kako bi artefakti bili reproducibilni.

In [25]:
def save_training_config(output_path: Path, selected_device: torch.device) -> None:
    payload = {
        "algorithm": ALGORITHM,
        "scenario": SCENARIO,
        "dataset_dir": str(FEDERATED_DATASET_DIR),
        "experiment_metadata_path": str(METADATA_PATH),
        "output_root": str(OUTPUT_ROOT),
        "run_dir": str(run_dir),
        "run_name": RUN_NAME,
        "device": str(selected_device),
        "seed": SEED,
        "debug_max_clients": DEBUG_MAX_CLIENTS,
        "model": {
            "input_size": EXPECTED_FEATURE_COUNT,
            "hidden_size": HIDDEN_SIZE,
            "num_layers": NUM_LAYERS,
            "dropout": DROPOUT,
        },
        "federated": {
            "num_rounds": NUM_ROUNDS,
            "local_epochs": LOCAL_EPOCHS,
            "fedprox_mu": FEDPROX_MU,
            "client_count_loaded": len(all_clients),
            "client_count_train": len(train_clients),
        },
        "optimization": {
            "batch_size": BATCH_SIZE,
            "lr": LR,
            "weight_decay": WEIGHT_DECAY,
            "grad_clip_norm": GRAD_CLIP_NORM,
        },
        "task": {
            "window_size": EXPECTED_WINDOW_SIZE,
            "horizon": int(metadata.get("horizon", SUPPORTED_HORIZON)),
            "target_column": metadata.get("target_column", SUPPORTED_TARGET_COLUMN),
            "feature_count": EXPECTED_FEATURE_COUNT,
        },
    }
    save_json(payload, output_path)


save_training_config(run_dir / "config.json", selected_device)

## 6. Model factory

Svaki klijent dobiva svjezu instancu istog `LSTMRegressor` modela i globalne tezine na pocetku lokalnog treninga.

In [26]:
def make_model() -> LSTMRegressor:
    return LSTMRegressor(
        input_size=EXPECTED_FEATURE_COUNT,
        hidden_size=HIDDEN_SIZE,
        num_layers=NUM_LAYERS,
        dropout=DROPOUT,
    )


global_model = make_model().to(selected_device)
loss_fn = nn.MSELoss()
parameter_count = count_trainable_parameters(global_model)
model_state_bytes = estimate_model_state_bytes(global_model)
best_model_path = run_dir / "best_model.pt"

pd.DataFrame(
    [
        {"item": "parameter_count", "value": parameter_count},
        {"item": "model_state_bytes", "value": model_state_bytes},
        {"item": "hidden_size", "value": HIDDEN_SIZE},
        {"item": "num_layers", "value": NUM_LAYERS},
        {"item": "dropout", "value": DROPOUT},
    ]
)

                item     value
0    parameter_count   76417.0
1  model_state_bytes  305668.0
2        hidden_size     128.0
3         num_layers       1.0
4            dropout       0.0

## Evaluation helpers

Ako projekt u buducnosti izveze `evaluate_split`, notebook ga moze preuzeti. Trenutno se koristi ista notebook funkcija kao u centralized LSTM-u.

In [27]:
def predict_split(
    *,
    model: nn.Module,
    split_arrays: SplitArrays,
    batch_size: int,
    device: torch.device,
) -> np.ndarray:
    model.eval()
    loader = build_dataloader(split_arrays, batch_size, shuffle=False, device=device)
    y_predictions: list[np.ndarray] = []

    with torch.no_grad():
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device=device, dtype=torch.float32, non_blocking=device.type == "cuda")
            y_batch = y_batch.to(device=device, dtype=torch.float32, non_blocking=device.type == "cuda")
            predictions = model(X_batch).squeeze(-1)
            if predictions.ndim == 0 and y_batch.numel() == 1:
                predictions = predictions.reshape_as(y_batch)
            if predictions.shape != y_batch.shape:
                raise RuntimeError(
                    f"Prediction shape {predictions.shape} does not match target shape {y_batch.shape}."
                )
            if not torch.isfinite(predictions).all():
                raise RuntimeError("Non-finite predictions encountered during evaluation.")
            y_predictions.append(predictions.cpu().numpy())

    return np.concatenate(y_predictions, axis=0)


if project_evaluate_split is not None:
    evaluate_split = project_evaluate_split
else:
    def evaluate_split(
        *,
        model: nn.Module,
        split_arrays: SplitArrays,
        batch_size: int,
        device: torch.device,
        loss_fn: nn.Module,
        method_name: str,
    ) -> dict[str, Any]:
        model.eval()
        loader = build_dataloader(split_arrays, batch_size, shuffle=False, device=device)
        total_loss = 0.0
        total_samples = 0
        y_predictions: list[np.ndarray] = []

        with torch.no_grad():
            for X_batch, y_batch in loader:
                X_batch = X_batch.to(device=device, dtype=torch.float32, non_blocking=device.type == "cuda")
                y_batch = y_batch.to(device=device, dtype=torch.float32, non_blocking=device.type == "cuda")

                predictions = model(X_batch).squeeze(-1)
                if predictions.ndim == 0 and y_batch.numel() == 1:
                    predictions = predictions.reshape_as(y_batch)
                if predictions.shape != y_batch.shape:
                    raise RuntimeError(
                        f"Prediction shape {predictions.shape} does not match target shape {y_batch.shape}."
                    )
                if not torch.isfinite(predictions).all():
                    raise RuntimeError("Non-finite predictions encountered during evaluation.")

                loss = loss_fn(predictions, y_batch)
                if not torch.isfinite(loss):
                    raise RuntimeError("Non-finite loss encountered during evaluation.")

                batch_size_actual = int(y_batch.shape[0])
                total_loss += float(loss.item()) * batch_size_actual
                total_samples += batch_size_actual
                y_predictions.append(predictions.cpu().numpy())

        if total_samples == 0:
            raise ValueError("Cannot evaluate an empty split.")

        y_pred = np.concatenate(y_predictions, axis=0)
        metrics = compute_regression_metrics(split_arrays.y, y_pred)
        prediction_frame = build_prediction_frame(
            t=split_arrays.t,
            station_ids=split_arrays.station_ids,
            y_true=split_arrays.y,
            y_pred=y_pred,
            method_name=method_name,
        )

        return {
            "loss": total_loss / total_samples,
            "metrics": metrics,
            "prediction_frame": prediction_frame,
        }


def empty_eval_result(method_name: str) -> dict[str, Any]:
    return {
        "loss": np.nan,
        "metrics": {"rmse": np.nan, "mae": np.nan, "r2": np.nan, "sample_count": 0},
        "prediction_frame": pd.DataFrame(
            columns=["t", "station_id", "y_true", "y_pred", "error", "abs_error", "method_name"]
        ),
    }


def evaluate_optional_split(
    *,
    model: nn.Module,
    split_arrays: SplitArrays | None,
    batch_size: int,
    device: torch.device,
    loss_fn: nn.Module,
    method_name: str,
) -> dict[str, Any]:
    if split_arrays is None or len(split_arrays.y) == 0:
        return empty_eval_result(method_name)
    return evaluate_split(
        model=model,
        split_arrays=split_arrays,
        batch_size=batch_size,
        device=device,
        loss_fn=loss_fn,
        method_name=method_name,
    )

## 7. Federated helper functions

FedAvg agregacija radi ponderirani prosjek po broju train uzoraka klijenta. Agregacija se radi na CPU-u radi jednostavnosti i ponovljivosti.

In [28]:
def clone_state_dict(state_dict: dict[str, torch.Tensor]) -> dict[str, torch.Tensor]:
    return {name: tensor.detach().cpu().clone() for name, tensor in state_dict.items()}


def state_dict_to_device(state_dict: dict[str, torch.Tensor], device: torch.device) -> dict[str, torch.Tensor]:
    return {name: tensor.detach().to(device) for name, tensor in state_dict.items()}


def fedavg_aggregate(
    client_states: list[dict[str, torch.Tensor]],
    client_sizes: list[int],
) -> dict[str, torch.Tensor]:
    if not client_states:
        raise ValueError("FedAvg requires at least one client state.")
    if len(client_states) != len(client_sizes):
        raise ValueError("client_states and client_sizes must have the same length.")

    sizes = np.asarray(client_sizes, dtype=np.float64)
    if (sizes <= 0).any():
        raise ValueError(f"All client sizes must be positive, got {client_sizes}.")
    total_size = float(sizes.sum())

    aggregated: dict[str, torch.Tensor] = {}
    for name in client_states[0].keys():
        first_tensor = client_states[0][name].detach().cpu()
        if torch.is_floating_point(first_tensor):
            accumulator_dtype = torch.float64 if first_tensor.dtype == torch.float64 else torch.float32
            accumulator = torch.zeros_like(first_tensor, dtype=accumulator_dtype, device="cpu")
            for state_dict, client_size in zip(client_states, sizes):
                local_tensor = state_dict[name].detach().cpu().to(dtype=accumulator_dtype)
                accumulator.add_(local_tensor, alpha=float(client_size / total_size))
            aggregated[name] = accumulator.to(dtype=first_tensor.dtype)
        else:
            aggregated[name] = first_tensor.clone()
    return aggregated

## 8. Local client training

Klijent u lokalnom treningu vidi samo svoj `train.npz`. Za FedProx se dodaje proksimalni clan prema zamrznutim globalnim parametrima.

In [29]:
def train_client(
    global_state_dict: dict[str, torch.Tensor],
    client: ClientDatasetBundle,
    model_fn,
    algorithm: str,
    local_epochs: int,
    batch_size: int,
    device: torch.device,
    lr: float,
    weight_decay: float,
    loss_fn: nn.Module,
    grad_clip_norm: float | None,
    fedprox_mu: float,
) -> tuple[dict[str, torch.Tensor], int, float]:
    num_samples = int(len(client.train.y))
    if num_samples == 0:
        raise ValueError(f"Client {client.client_id} has an empty train split.")

    normalized_algorithm = algorithm.strip().lower()
    if normalized_algorithm not in {"fedavg", "fedprox"}:
        raise ValueError("algorithm must be 'fedavg' or 'fedprox'.")

    local_model = model_fn().to(device)
    local_model.load_state_dict(state_dict_to_device(global_state_dict, device))
    local_model.train()

    global_parameters = {
        name: parameter.detach().clone().to(device)
        for name, parameter in local_model.named_parameters()
        if torch.is_floating_point(parameter)
    }
    for parameter in global_parameters.values():
        parameter.requires_grad_(False)

    optimizer = torch.optim.Adam(local_model.parameters(), lr=lr, weight_decay=weight_decay)
    loader = build_dataloader(client.train, batch_size, shuffle=True, device=device)

    total_loss = 0.0
    total_seen = 0
    for _ in range(local_epochs):
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device=device, dtype=torch.float32, non_blocking=device.type == "cuda")
            y_batch = y_batch.to(device=device, dtype=torch.float32, non_blocking=device.type == "cuda")

            optimizer.zero_grad(set_to_none=True)
            predictions = local_model(X_batch).squeeze(-1)
            if predictions.ndim == 0 and y_batch.numel() == 1:
                predictions = predictions.reshape_as(y_batch)
            if predictions.shape != y_batch.shape:
                raise RuntimeError(
                    f"Prediction shape {predictions.shape} does not match target shape {y_batch.shape} "
                    f"on {client.client_id}."
                )
            if not torch.isfinite(predictions).all():
                raise RuntimeError(f"Non-finite predictions encountered on {client.client_id}.")

            mse_loss = loss_fn(predictions, y_batch)
            if normalized_algorithm == "fedprox":
                proximal_term = torch.zeros((), device=device, dtype=mse_loss.dtype)
                for name, local_parameter in local_model.named_parameters():
                    if torch.is_floating_point(local_parameter):
                        proximal_term = proximal_term + torch.sum((local_parameter - global_parameters[name]) ** 2)
                loss = mse_loss + (fedprox_mu / 2.0) * proximal_term
            else:
                loss = mse_loss

            if not torch.isfinite(loss):
                raise RuntimeError(f"Non-finite loss encountered on {client.client_id}.")

            loss.backward()
            if grad_clip_norm is not None and grad_clip_norm > 0.0:
                clip_grad_norm_(local_model.parameters(), grad_clip_norm)
            optimizer.step()

            batch_size_actual = int(y_batch.shape[0])
            total_loss += float(loss.item()) * batch_size_actual
            total_seen += batch_size_actual

    average_loss = total_loss / total_seen
    return clone_state_dict(local_model.state_dict()), num_samples, float(average_loss)

## 9. Global evaluation

Globalni train/val/test skupovi nastaju samo konkatenacijom istoimenih splitova. Prazni val/test splitovi pojedinih klijenata se ne ukljucuju.

In [30]:
method_name = f"{ALGORITHM}_lstm_{SCENARIO}"

global_split_overview = pd.DataFrame(
    [
        {"split": "train", "samples": int(len(global_train.y)), "X_shape": tuple(global_train.X.shape)},
        {"split": "val", "samples": int(len(global_val.y)), "X_shape": tuple(global_val.X.shape)},
        {
            "split": "test",
            "samples": 0 if global_test is None else int(len(global_test.y)),
            "X_shape": None if global_test is None else tuple(global_test.X.shape),
        },
    ]
)

global_split_overview

   split  samples           X_shape
0  train   110642  (110642, 24, 19)
1    val     6824    (6824, 24, 19)
2   test    30275   (30275, 24, 19)

## 10. Federated training loop

U svakoj rundi saljemo trenutni globalni `state_dict` svim trenirajucim klijentima, lokalno treniramo, agregiramo i validiramo globalni model.

In [ ]:
round_rows: list[dict[str, Any]] = []
best_val_rmse = float("inf")
best_round: int | None = None

global_state = clone_state_dict(global_model.state_dict())

for round_idx in range(1, NUM_ROUNDS + 1):
    client_states: list[dict[str, torch.Tensor]] = []
    client_sizes: list[int] = []
    client_losses: list[float] = []

    for client in train_clients:
        local_state, num_samples, local_loss = train_client(
            global_state_dict=global_state,
            client=client,
            model_fn=make_model,
            algorithm=ALGORITHM,
            local_epochs=LOCAL_EPOCHS,
            batch_size=BATCH_SIZE,
            device=selected_device,
            lr=LR,
            weight_decay=WEIGHT_DECAY,
            loss_fn=loss_fn,
            grad_clip_norm=GRAD_CLIP_NORM,
            fedprox_mu=FEDPROX_MU,
        )
        client_states.append(local_state)
        client_sizes.append(num_samples)
        client_losses.append(local_loss)

    global_state = fedavg_aggregate(client_states, client_sizes)
    global_model.load_state_dict(state_dict_to_device(global_state, selected_device))

    val_eval = evaluate_split(
        model=global_model,
        split_arrays=global_val,
        batch_size=BATCH_SIZE,
        device=selected_device,
        loss_fn=loss_fn,
        method_name=method_name,
    )
    val_metrics = val_eval["metrics"]
    train_loss_mean = float(np.mean(client_losses))
    train_loss_weighted = float(np.average(client_losses, weights=np.asarray(client_sizes, dtype=float)))
    communication_upload_bytes = model_state_bytes * len(train_clients)
    communication_download_bytes = model_state_bytes * len(train_clients)
    communication_total_bytes = communication_upload_bytes + communication_download_bytes
    communication_cumulative_bytes = communication_total_bytes * round_idx

    row = {
        "round": round_idx,
        "client_count": len(train_clients),
        "train_loss_mean": train_loss_mean,
        "train_loss_weighted": train_loss_weighted,
        "val_loss": float(val_eval["loss"]),
        "val_mae": float(val_metrics["mae"]),
        "val_rmse": float(val_metrics["rmse"]),
        "val_smape": float(val_metrics.get("smape", np.nan)),
        "val_mape": float(val_metrics.get("mape", np.nan)),
        "val_r2": float(val_metrics["r2"]),
        "communication_upload_mb": communication_upload_bytes / (1024 ** 2),
        "communication_download_mb": communication_download_bytes / (1024 ** 2),
        "communication_total_mb": communication_total_bytes / (1024 ** 2),
        "communication_cumulative_mb": communication_cumulative_bytes / (1024 ** 2),
    }
    round_rows.append(row)
    pd.DataFrame(round_rows).to_csv(run_dir / "round_metrics.csv", index=False)

    print(
        f"Round {round_idx}/{NUM_ROUNDS} | "
        f"train_loss={train_loss_weighted:.6f} | "
        f"val_rmse={row['val_rmse']:.6f} | "
        f"val_mae={row['val_mae']:.6f} | "
        f"val_r2={row['val_r2']:.6f}"
    )
    logger.info(
        "Round %d/%d | train_loss=%.6f | val_rmse=%.6f | val_mae=%.6f | val_r2=%.6f",
        round_idx,
        NUM_ROUNDS,
        train_loss_weighted,
        row["val_rmse"],
        row["val_mae"],
        row["val_r2"],
    )

    if row["val_rmse"] < best_val_rmse:
        best_val_rmse = row["val_rmse"]
        best_round = round_idx
        torch.save(global_state, best_model_path)
        logger.info("Saved new best model at round %d with val_rmse=%.6f", round_idx, best_val_rmse)

if best_round is None:
    raise RuntimeError("Training finished without producing a valid checkpoint.")

round_metrics = pd.DataFrame(round_rows)
round_metrics

2026-05-11 18:44:26,107 | INFO | Round 1/100 | train_loss=1576758.111503 | val_rmse=1010.747532 | val_mae=330.679216 | val_r2=-0.116787
2026-05-11 18:44:26,167 | INFO | Saved new best model at round 1 with val_rmse=1010.747532

Round 1/100 | train_loss=1576758.111503 | val_rmse=1010.747532 | val_mae=330.679216 | val_r2=-0.116787

2026-05-11 18:45:19,434 | INFO | Round 2/100 | train_loss=1570737.572976 | val_rmse=1009.161588 | val_mae=327.461372 | val_r2=-0.113286
2026-05-11 18:45:19,510 | INFO | Saved new best model at round 2 with val_rmse=1009.161588

Round 2/100 | train_loss=1570737.572976 | val_rmse=1009.161588 | val_mae=327.461372 | val_r2=-0.113286

2026-05-11 18:46:13,184 | INFO | Round 3/100 | train_loss=1566894.779856 | val_rmse=1007.802786 | val_mae=324.659396 | val_r2=-0.110290
2026-05-11 18:46:13,239 | INFO | Saved new best model at round 3 with val_rmse=1007.802786

Round 3/100 | train_loss=1566894.779856 | val_rmse=1007.802786 | val_mae=324.659396 | val_r2=-0.110290

2026-05-11 18:47:07,747 | INFO | Round 4/100 | train_loss=1563263.695708 | val_rmse=1006.476695 | val_mae=322.699314 | val_r2=-0.107370
2026-05-11 18:47:07,860 | INFO | Saved new best model at round 4 with val_rmse=1006.476695

Round 4/100 | train_loss=1563263.695708 | val_rmse=1006.476695 | val_mae=322.699314 | val_r2=-0.107370

2026-05-11 18:48:02,062 | INFO | Round 5/100 | train_loss=1559658.639096 | val_rmse=1005.146205 | val_mae=321.279371 | val_r2=-0.104444
2026-05-11 18:48:02,125 | INFO | Saved new best model at round 5 with val_rmse=1005.146205

Round 5/100 | train_loss=1559658.639096 | val_rmse=1005.146205 | val_mae=321.279371 | val_r2=-0.104444

2026-05-11 18:48:57,180 | INFO | Round 6/100 | train_loss=1556035.475977 | val_rmse=1003.817628 | val_mae=319.129532 | val_r2=-0.101526
2026-05-11 18:48:57,235 | INFO | Saved new best model at round 6 with val_rmse=1003.817628

Round 6/100 | train_loss=1556035.475977 | val_rmse=1003.817628 | val_mae=319.129532 | val_r2=-0.101526

2026-05-11 18:49:52,766 | INFO | Round 7/100 | train_loss=1552431.922416 | val_rmse=1002.487159 | val_mae=316.727909 | val_r2=-0.098608
2026-05-11 18:49:52,822 | INFO | Saved new best model at round 7 with val_rmse=1002.487159

Round 7/100 | train_loss=1552431.922416 | val_rmse=1002.487159 | val_mae=316.727909 | val_r2=-0.098608

2026-05-11 18:50:46,650 | INFO | Round 8/100 | train_loss=1548851.280573 | val_rmse=1001.165528 | val_mae=314.245509 | val_r2=-0.095713
2026-05-11 18:50:46,705 | INFO | Saved new best model at round 8 with val_rmse=1001.165528

Round 8/100 | train_loss=1548851.280573 | val_rmse=1001.165528 | val_mae=314.245509 | val_r2=-0.095713

2026-05-11 18:51:40,818 | INFO | Round 9/100 | train_loss=1545291.124243 | val_rmse=999.858855 | val_mae=312.614127 | val_r2=-0.092855
2026-05-11 18:51:40,902 | INFO | Saved new best model at round 9 with val_rmse=999.858855

Round 9/100 | train_loss=1545291.124243 | val_rmse=999.858855 | val_mae=312.614127 | val_r2=-0.092855

2026-05-11 18:52:34,566 | INFO | Round 10/100 | train_loss=1541744.733246 | val_rmse=998.555884 | val_mae=310.991534 | val_r2=-0.090009
2026-05-11 18:52:34,628 | INFO | Saved new best model at round 10 with val_rmse=998.555884

Round 10/100 | train_loss=1541744.733246 | val_rmse=998.555884 | val_mae=310.991534 | val_r2=-0.090009

2026-05-11 18:53:28,628 | INFO | Round 11/100 | train_loss=1538211.652408 | val_rmse=997.258527 | val_mae=309.425912 | val_r2=-0.087178
2026-05-11 18:53:28,694 | INFO | Saved new best model at round 11 with val_rmse=997.258527

Round 11/100 | train_loss=1538211.652408 | val_rmse=997.258527 | val_mae=309.425912 | val_r2=-0.087178

2026-05-11 18:54:24,342 | INFO | Round 12/100 | train_loss=1534698.380276 | val_rmse=995.966087 | val_mae=308.058854 | val_r2=-0.084362
2026-05-11 18:54:24,443 | INFO | Saved new best model at round 12 with val_rmse=995.966087

Round 12/100 | train_loss=1534698.380276 | val_rmse=995.966087 | val_mae=308.058854 | val_r2=-0.084362

2026-05-11 18:55:18,811 | INFO | Round 13/100 | train_loss=1531196.125050 | val_rmse=994.677941 | val_mae=306.727706 | val_r2=-0.081559
2026-05-11 18:55:18,876 | INFO | Saved new best model at round 13 with val_rmse=994.677941

Round 13/100 | train_loss=1531196.125050 | val_rmse=994.677941 | val_mae=306.727706 | val_r2=-0.081559

2026-05-11 18:56:13,128 | INFO | Round 14/100 | train_loss=1527710.089877 | val_rmse=993.394548 | val_mae=305.552858 | val_r2=-0.078770
2026-05-11 18:56:13,185 | INFO | Saved new best model at round 14 with val_rmse=993.394548

Round 14/100 | train_loss=1527710.089877 | val_rmse=993.394548 | val_mae=305.552858 | val_r2=-0.078770

2026-05-11 18:57:06,219 | INFO | Round 15/100 | train_loss=1524237.657372 | val_rmse=992.115643 | val_mae=304.465810 | val_r2=-0.075994
2026-05-11 18:57:06,291 | INFO | Saved new best model at round 15 with val_rmse=992.115643

Round 15/100 | train_loss=1524237.657372 | val_rmse=992.115643 | val_mae=304.465810 | val_r2=-0.075994

2026-05-11 18:58:00,518 | INFO | Round 16/100 | train_loss=1520775.274546 | val_rmse=990.840028 | val_mae=303.442630 | val_r2=-0.073229
2026-05-11 18:58:00,595 | INFO | Saved new best model at round 16 with val_rmse=990.840028

Round 16/100 | train_loss=1520775.274546 | val_rmse=990.840028 | val_mae=303.442630 | val_r2=-0.073229

2026-05-11 18:58:53,741 | INFO | Round 17/100 | train_loss=1517328.059785 | val_rmse=989.568148 | val_mae=302.392662 | val_r2=-0.070475
2026-05-11 18:58:53,793 | INFO | Saved new best model at round 17 with val_rmse=989.568148

Round 17/100 | train_loss=1517328.059785 | val_rmse=989.568148 | val_mae=302.392662 | val_r2=-0.070475

2026-05-11 18:59:47,706 | INFO | Round 18/100 | train_loss=1513887.351652 | val_rmse=988.299348 | val_mae=301.434715 | val_r2=-0.067732
2026-05-11 18:59:47,795 | INFO | Saved new best model at round 18 with val_rmse=988.299348

Round 18/100 | train_loss=1513887.351652 | val_rmse=988.299348 | val_mae=301.434715 | val_r2=-0.067732

2026-05-11 19:00:41,447 | INFO | Round 19/100 | train_loss=1510466.484909 | val_rmse=987.033815 | val_mae=300.477962 | val_r2=-0.064999
2026-05-11 19:00:41,533 | INFO | Saved new best model at round 19 with val_rmse=987.033815

Round 19/100 | train_loss=1510466.484909 | val_rmse=987.033815 | val_mae=300.477962 | val_r2=-0.064999

2026-05-11 19:01:35,322 | INFO | Round 20/100 | train_loss=1507045.375208 | val_rmse=985.770440 | val_mae=299.532133 | val_r2=-0.062274
2026-05-11 19:01:35,382 | INFO | Saved new best model at round 20 with val_rmse=985.770440

Round 20/100 | train_loss=1507045.375208 | val_rmse=985.770440 | val_mae=299.532133 | val_r2=-0.062274

2026-05-11 19:02:30,282 | INFO | Round 21/100 | train_loss=1503638.804451 | val_rmse=984.509176 | val_mae=298.541137 | val_r2=-0.059558
2026-05-11 19:02:30,341 | INFO | Saved new best model at round 21 with val_rmse=984.509176

Round 21/100 | train_loss=1503638.804451 | val_rmse=984.509176 | val_mae=298.541137 | val_r2=-0.059558

2026-05-11 19:03:23,635 | INFO | Round 22/100 | train_loss=1500244.017442 | val_rmse=983.252726 | val_mae=297.643699 | val_r2=-0.056855
2026-05-11 19:03:23,696 | INFO | Saved new best model at round 22 with val_rmse=983.252726

Round 22/100 | train_loss=1500244.017442 | val_rmse=983.252726 | val_mae=297.643699 | val_r2=-0.056855

2026-05-11 19:04:19,051 | INFO | Round 23/100 | train_loss=1496857.776281 | val_rmse=981.998111 | val_mae=296.772061 | val_r2=-0.054160
2026-05-11 19:04:19,117 | INFO | Saved new best model at round 23 with val_rmse=981.998111

Round 23/100 | train_loss=1496857.776281 | val_rmse=981.998111 | val_mae=296.772061 | val_r2=-0.054160

2026-05-11 19:05:12,628 | INFO | Round 24/100 | train_loss=1493488.069776 | val_rmse=980.746635 | val_mae=295.935367 | val_r2=-0.051475
2026-05-11 19:05:12,703 | INFO | Saved new best model at round 24 with val_rmse=980.746635

Round 24/100 | train_loss=1493488.069776 | val_rmse=980.746635 | val_mae=295.935367 | val_r2=-0.051475

2026-05-11 19:06:06,520 | INFO | Round 25/100 | train_loss=1490119.026211 | val_rmse=979.498224 | val_mae=295.146089 | val_r2=-0.048799
2026-05-11 19:06:06,572 | INFO | Saved new best model at round 25 with val_rmse=979.498224

Round 25/100 | train_loss=1490119.026211 | val_rmse=979.498224 | val_mae=295.146089 | val_r2=-0.048799

2026-05-11 19:07:00,566 | INFO | Round 26/100 | train_loss=1486767.382968 | val_rmse=978.252028 | val_mae=294.370528 | val_r2=-0.046132
2026-05-11 19:07:00,639 | INFO | Saved new best model at round 26 with val_rmse=978.252028

Round 26/100 | train_loss=1486767.382968 | val_rmse=978.252028 | val_mae=294.370528 | val_r2=-0.046132

2026-05-11 19:07:54,576 | INFO | Round 27/100 | train_loss=1483418.923326 | val_rmse=977.008292 | val_mae=293.580928 | val_r2=-0.043474
2026-05-11 19:07:54,649 | INFO | Saved new best model at round 27 with val_rmse=977.008292

Round 27/100 | train_loss=1483418.923326 | val_rmse=977.008292 | val_mae=293.580928 | val_r2=-0.043474

2026-05-11 19:08:49,247 | INFO | Round 28/100 | train_loss=1480085.179303 | val_rmse=975.767907 | val_mae=292.881436 | val_r2=-0.040826
2026-05-11 19:08:49,305 | INFO | Saved new best model at round 28 with val_rmse=975.767907

Round 28/100 | train_loss=1480085.179303 | val_rmse=975.767907 | val_mae=292.881436 | val_r2=-0.040826

2026-05-11 19:09:42,778 | INFO | Round 29/100 | train_loss=1476755.839286 | val_rmse=974.526981 | val_mae=292.133005 | val_r2=-0.038181
2026-05-11 19:09:42,858 | INFO | Saved new best model at round 29 with val_rmse=974.526981

Round 29/100 | train_loss=1476755.839286 | val_rmse=974.526981 | val_mae=292.133005 | val_r2=-0.038181

2026-05-11 19:10:36,440 | INFO | Round 30/100 | train_loss=1473437.427524 | val_rmse=973.288344 | val_mae=291.421968 | val_r2=-0.035543
2026-05-11 19:10:36,506 | INFO | Saved new best model at round 30 with val_rmse=973.288344

Round 30/100 | train_loss=1473437.427524 | val_rmse=973.288344 | val_mae=291.421968 | val_r2=-0.035543

2026-05-11 19:11:29,714 | INFO | Round 31/100 | train_loss=1470120.813637 | val_rmse=972.052622 | val_mae=290.742158 | val_r2=-0.032915
2026-05-11 19:11:29,796 | INFO | Saved new best model at round 31 with val_rmse=972.052622

Round 31/100 | train_loss=1470120.813637 | val_rmse=972.052622 | val_mae=290.742158 | val_r2=-0.032915

2026-05-11 19:12:23,330 | INFO | Round 32/100 | train_loss=1466819.552116 | val_rmse=970.814197 | val_mae=290.005551 | val_r2=-0.030285
2026-05-11 19:12:23,427 | INFO | Saved new best model at round 32 with val_rmse=970.814197

Round 32/100 | train_loss=1466819.552116 | val_rmse=970.814197 | val_mae=290.005551 | val_r2=-0.030285

2026-05-11 19:13:18,099 | INFO | Round 33/100 | train_loss=1463523.132588 | val_rmse=969.583992 | val_mae=289.389033 | val_r2=-0.027676
2026-05-11 19:13:18,160 | INFO | Saved new best model at round 33 with val_rmse=969.583992

Round 33/100 | train_loss=1463523.132588 | val_rmse=969.583992 | val_mae=289.389033 | val_r2=-0.027676

2026-05-11 19:14:12,526 | INFO | Round 34/100 | train_loss=1460236.996634 | val_rmse=968.354426 | val_mae=288.709913 | val_r2=-0.025071
2026-05-11 19:14:12,619 | INFO | Saved new best model at round 34 with val_rmse=968.354426

Round 34/100 | train_loss=1460236.996634 | val_rmse=968.354426 | val_mae=288.709913 | val_r2=-0.025071

2026-05-11 19:15:05,413 | INFO | Round 35/100 | train_loss=1456957.566444 | val_rmse=967.123839 | val_mae=288.043000 | val_r2=-0.022467
2026-05-11 19:15:05,474 | INFO | Saved new best model at round 35 with val_rmse=967.123839

Round 35/100 | train_loss=1456957.566444 | val_rmse=967.123839 | val_mae=288.043000 | val_r2=-0.022467

2026-05-11 19:16:00,502 | INFO | Round 36/100 | train_loss=1453683.722015 | val_rmse=965.898132 | val_mae=287.438825 | val_r2=-0.019877
2026-05-11 19:16:00,561 | INFO | Saved new best model at round 36 with val_rmse=965.898132

Round 36/100 | train_loss=1453683.722015 | val_rmse=965.898132 | val_mae=287.438825 | val_r2=-0.019877

2026-05-11 19:16:53,658 | INFO | Round 37/100 | train_loss=1450425.495061 | val_rmse=964.673718 | val_mae=286.828693 | val_r2=-0.017293
2026-05-11 19:16:53,726 | INFO | Saved new best model at round 37 with val_rmse=964.673718

Round 37/100 | train_loss=1450425.495061 | val_rmse=964.673718 | val_mae=286.828693 | val_r2=-0.017293

2026-05-11 19:17:46,995 | INFO | Round 38/100 | train_loss=1447162.014142 | val_rmse=963.443646 | val_mae=286.136410 | val_r2=-0.014700
2026-05-11 19:17:47,058 | INFO | Saved new best model at round 38 with val_rmse=963.443646

Round 38/100 | train_loss=1447162.014142 | val_rmse=963.443646 | val_mae=286.136410 | val_r2=-0.014700

2026-05-11 19:18:39,702 | INFO | Round 39/100 | train_loss=1443916.986183 | val_rmse=962.219472 | val_mae=285.489768 | val_r2=-0.012123
2026-05-11 19:18:39,786 | INFO | Saved new best model at round 39 with val_rmse=962.219472

Round 39/100 | train_loss=1443916.986183 | val_rmse=962.219472 | val_mae=285.489768 | val_r2=-0.012123

2026-05-11 19:19:34,160 | INFO | Round 40/100 | train_loss=1440675.920006 | val_rmse=960.997674 | val_mae=284.851605 | val_r2=-0.009555
2026-05-11 19:19:34,252 | INFO | Saved new best model at round 40 with val_rmse=960.997674

Round 40/100 | train_loss=1440675.920006 | val_rmse=960.997674 | val_mae=284.851605 | val_r2=-0.009555

2026-05-11 19:20:28,169 | INFO | Round 41/100 | train_loss=1437439.678224 | val_rmse=959.771550 | val_mae=284.143004 | val_r2=-0.006980
2026-05-11 19:20:28,233 | INFO | Saved new best model at round 41 with val_rmse=959.771550

Round 41/100 | train_loss=1437439.678224 | val_rmse=959.771550 | val_mae=284.143004 | val_r2=-0.006980

2026-05-11 19:21:21,177 | INFO | Round 42/100 | train_loss=1434215.208740 | val_rmse=958.550594 | val_mae=283.503161 | val_r2=-0.004420
2026-05-11 19:21:21,258 | INFO | Saved new best model at round 42 with val_rmse=958.550594

Round 42/100 | train_loss=1434215.208740 | val_rmse=958.550594 | val_mae=283.503161 | val_r2=-0.004420

2026-05-11 19:22:15,289 | INFO | Round 43/100 | train_loss=1430991.722433 | val_rmse=957.328556 | val_mae=282.841115 | val_r2=-0.001860
2026-05-11 19:22:15,358 | INFO | Saved new best model at round 43 with val_rmse=957.328556

Round 43/100 | train_loss=1430991.722433 | val_rmse=957.328556 | val_mae=282.841115 | val_r2=-0.001860

2026-05-11 19:23:08,618 | INFO | Round 44/100 | train_loss=1427777.706571 | val_rmse=956.111248 | val_mae=282.205982 | val_r2=0.000686
2026-05-11 19:23:08,683 | INFO | Saved new best model at round 44 with val_rmse=956.111248

Round 44/100 | train_loss=1427777.706571 | val_rmse=956.111248 | val_mae=282.205982 | val_r2=0.000686

2026-05-11 19:24:03,890 | INFO | Round 45/100 | train_loss=1424570.482089 | val_rmse=954.898700 | val_mae=281.631601 | val_r2=0.003219
2026-05-11 19:24:03,952 | INFO | Saved new best model at round 45 with val_rmse=954.898700

Round 45/100 | train_loss=1424570.482089 | val_rmse=954.898700 | val_mae=281.631601 | val_r2=0.003219

2026-05-11 19:24:56,845 | INFO | Round 46/100 | train_loss=1421368.809804 | val_rmse=953.683771 | val_mae=280.959509 | val_r2=0.005754
2026-05-11 19:24:56,899 | INFO | Saved new best model at round 46 with val_rmse=953.683771

Round 46/100 | train_loss=1421368.809804 | val_rmse=953.683771 | val_mae=280.959509 | val_r2=0.005754

2026-05-11 19:25:50,949 | INFO | Round 47/100 | train_loss=1418176.227371 | val_rmse=952.467534 | val_mae=280.341094 | val_r2=0.008288
2026-05-11 19:25:51,037 | INFO | Saved new best model at round 47 with val_rmse=952.467534

Round 47/100 | train_loss=1418176.227371 | val_rmse=952.467534 | val_mae=280.341094 | val_r2=0.008288

2026-05-11 19:26:45,030 | INFO | Round 48/100 | train_loss=1414985.398962 | val_rmse=951.265012 | val_mae=279.747354 | val_r2=0.010791
2026-05-11 19:26:45,115 | INFO | Saved new best model at round 48 with val_rmse=951.265012

Round 48/100 | train_loss=1414985.398962 | val_rmse=951.265012 | val_mae=279.747354 | val_r2=0.010791

2026-05-11 19:27:39,709 | INFO | Round 49/100 | train_loss=1411806.837283 | val_rmse=950.057549 | val_mae=279.166077 | val_r2=0.013300
2026-05-11 19:27:39,772 | INFO | Saved new best model at round 49 with val_rmse=950.057549

Round 49/100 | train_loss=1411806.837283 | val_rmse=950.057549 | val_mae=279.166077 | val_r2=0.013300

2026-05-11 19:28:34,170 | INFO | Round 50/100 | train_loss=1408629.660401 | val_rmse=948.845138 | val_mae=278.517175 | val_r2=0.015817
2026-05-11 19:28:34,254 | INFO | Saved new best model at round 50 with val_rmse=948.845138

Round 50/100 | train_loss=1408629.660401 | val_rmse=948.845138 | val_mae=278.517175 | val_r2=0.015817

2026-05-11 19:29:28,961 | INFO | Round 51/100 | train_loss=1405462.226210 | val_rmse=947.634991 | val_mae=277.911403 | val_r2=0.018326
2026-05-11 19:29:29,065 | INFO | Saved new best model at round 51 with val_rmse=947.634991

Round 51/100 | train_loss=1405462.226210 | val_rmse=947.634991 | val_mae=277.911403 | val_r2=0.018326

2026-05-11 19:30:21,988 | INFO | Round 52/100 | train_loss=1402306.913572 | val_rmse=946.428544 | val_mae=277.295660 | val_r2=0.020824
2026-05-11 19:30:22,063 | INFO | Saved new best model at round 52 with val_rmse=946.428544

Round 52/100 | train_loss=1402306.913572 | val_rmse=946.428544 | val_mae=277.295660 | val_r2=0.020824

2026-05-11 19:31:15,750 | INFO | Round 53/100 | train_loss=1399150.783970 | val_rmse=945.232629 | val_mae=276.714949 | val_r2=0.023297
2026-05-11 19:31:15,805 | INFO | Saved new best model at round 53 with val_rmse=945.232629

Round 53/100 | train_loss=1399150.783970 | val_rmse=945.232629 | val_mae=276.714949 | val_r2=0.023297

2026-05-11 19:32:09,910 | INFO | Round 54/100 | train_loss=1396010.324480 | val_rmse=944.010554 | val_mae=276.019524 | val_r2=0.025821
2026-05-11 19:32:09,974 | INFO | Saved new best model at round 54 with val_rmse=944.010554

Round 54/100 | train_loss=1396010.324480 | val_rmse=944.010554 | val_mae=276.019524 | val_r2=0.025821

2026-05-11 19:33:02,260 | INFO | Round 55/100 | train_loss=1392874.641961 | val_rmse=942.812710 | val_mae=275.468032 | val_r2=0.028292
2026-05-11 19:33:02,319 | INFO | Saved new best model at round 55 with val_rmse=942.812710

Round 55/100 | train_loss=1392874.641961 | val_rmse=942.812710 | val_mae=275.468032 | val_r2=0.028292

2026-05-11 19:33:54,219 | INFO | Round 56/100 | train_loss=1389732.562991 | val_rmse=941.626018 | val_mae=274.949203 | val_r2=0.030736
2026-05-11 19:33:54,269 | INFO | Saved new best model at round 56 with val_rmse=941.626018

Round 56/100 | train_loss=1389732.562991 | val_rmse=941.626018 | val_mae=274.949203 | val_r2=0.030736

2026-05-11 19:34:49,404 | INFO | Round 57/100 | train_loss=1386600.683519 | val_rmse=940.427026 | val_mae=274.357542 | val_r2=0.033203
2026-05-11 19:34:49,461 | INFO | Saved new best model at round 57 with val_rmse=940.427026

Round 57/100 | train_loss=1386600.683519 | val_rmse=940.427026 | val_mae=274.357542 | val_r2=0.033203

2026-05-11 19:37:26,356 | INFO | Saved new best model at round 60 with val_rmse=936.838774

Round 60/100 | train_loss=1377262.028359 | val_rmse=936.838774 | val_mae=272.533462 | val_r2=0.040567

2026-05-11 19:38:20,694 | INFO | Round 61/100 | train_loss=1374160.098293 | val_rmse=935.646279 | val_mae=271.925494 | val_r2=0.043008
2026-05-11 19:38:20,756 | INFO | Saved new best model at round 61 with val_rmse=935.646279

Round 61/100 | train_loss=1374160.098293 | val_rmse=935.646279 | val_mae=271.925494 | val_r2=0.043008

2026-05-11 19:39:15,833 | INFO | Round 62/100 | train_loss=1371061.378602 | val_rmse=934.445328 | val_mae=271.356030 | val_r2=0.045463
2026-05-11 19:39:15,898 | INFO | Saved new best model at round 62 with val_rmse=934.445328

Round 62/100 | train_loss=1371061.378602 | val_rmse=934.445328 | val_mae=271.356030 | val_r2=0.045463

2026-05-11 19:40:09,686 | INFO | Round 63/100 | train_loss=1367976.653427 | val_rmse=933.252362 | val_mae=270.733603 | val_r2=0.047898
2026-05-11 19:40:09,751 | INFO | Saved new best model at round 63 with val_rmse=933.252362

Round 63/100 | train_loss=1367976.653427 | val_rmse=933.252362 | val_mae=270.733603 | val_r2=0.047898

2026-05-11 19:41:03,449 | INFO | Round 64/100 | train_loss=1364895.459345 | val_rmse=932.063310 | val_mae=270.156708 | val_r2=0.050323
2026-05-11 19:41:03,508 | INFO | Saved new best model at round 64 with val_rmse=932.063310

Round 64/100 | train_loss=1364895.459345 | val_rmse=932.063310 | val_mae=270.156708 | val_r2=0.050323

2026-05-11 19:41:59,049 | INFO | Round 65/100 | train_loss=1361814.733674 | val_rmse=930.873489 | val_mae=269.575074 | val_r2=0.052746
2026-05-11 19:41:59,101 | INFO | Saved new best model at round 65 with val_rmse=930.873489

Round 65/100 | train_loss=1361814.733674 | val_rmse=930.873489 | val_mae=269.575074 | val_r2=0.052746

2026-05-11 19:42:52,687 | INFO | Round 66/100 | train_loss=1358750.708600 | val_rmse=929.688172 | val_mae=269.029614 | val_r2=0.055157
2026-05-11 19:42:52,739 | INFO | Saved new best model at round 66 with val_rmse=929.688172

Round 66/100 | train_loss=1358750.708600 | val_rmse=929.688172 | val_mae=269.029614 | val_r2=0.055157

2026-05-11 19:43:47,127 | INFO | Round 67/100 | train_loss=1355679.302013 | val_rmse=928.489015 | val_mae=268.381088 | val_r2=0.057593
2026-05-11 19:43:47,179 | INFO | Saved new best model at round 67 with val_rmse=928.489015

Round 67/100 | train_loss=1355679.302013 | val_rmse=928.489015 | val_mae=268.381088 | val_r2=0.057593

2026-05-11 19:44:42,661 | INFO | Round 68/100 | train_loss=1352629.976957 | val_rmse=927.322334 | val_mae=267.841634 | val_r2=0.059959
2026-05-11 19:44:42,716 | INFO | Saved new best model at round 68 with val_rmse=927.322334

Round 68/100 | train_loss=1352629.976957 | val_rmse=927.322334 | val_mae=267.841634 | val_r2=0.059959

2026-05-11 19:45:36,869 | INFO | Round 69/100 | train_loss=1349582.638841 | val_rmse=926.124287 | val_mae=267.229916 | val_r2=0.062387
2026-05-11 19:45:36,924 | INFO | Saved new best model at round 69 with val_rmse=926.124287

Round 69/100 | train_loss=1349582.638841 | val_rmse=926.124287 | val_mae=267.229916 | val_r2=0.062387

2026-05-11 19:46:31,611 | INFO | Round 70/100 | train_loss=1346540.967179 | val_rmse=924.953648 | val_mae=266.684631 | val_r2=0.064756
2026-05-11 19:46:31,678 | INFO | Saved new best model at round 70 with val_rmse=924.953648

Round 70/100 | train_loss=1346540.967179 | val_rmse=924.953648 | val_mae=266.684631 | val_r2=0.064756

2026-05-11 19:47:25,641 | INFO | Round 71/100 | train_loss=1343506.793861 | val_rmse=923.770570 | val_mae=266.130408 | val_r2=0.067147
2026-05-11 19:47:25,740 | INFO | Saved new best model at round 71 with val_rmse=923.770570

Round 71/100 | train_loss=1343506.793861 | val_rmse=923.770570 | val_mae=266.130408 | val_r2=0.067147

2026-05-11 19:48:19,406 | INFO | Round 72/100 | train_loss=1340481.441657 | val_rmse=922.587732 | val_mae=265.558705 | val_r2=0.069534
2026-05-11 19:48:19,456 | INFO | Saved new best model at round 72 with val_rmse=922.587732

Round 72/100 | train_loss=1340481.441657 | val_rmse=922.587732 | val_mae=265.558705 | val_r2=0.069534

2026-05-11 19:49:13,548 | INFO | Round 73/100 | train_loss=1337455.933717 | val_rmse=921.415476 | val_mae=264.958435 | val_r2=0.071897
2026-05-11 19:49:13,603 | INFO | Saved new best model at round 73 with val_rmse=921.415476

Round 73/100 | train_loss=1337455.933717 | val_rmse=921.415476 | val_mae=264.958435 | val_r2=0.071897

2026-05-11 19:50:06,708 | INFO | Round 74/100 | train_loss=1334443.241936 | val_rmse=920.237064 | val_mae=264.358508 | val_r2=0.074269
2026-05-11 19:50:06,758 | INFO | Saved new best model at round 74 with val_rmse=920.237064

Round 74/100 | train_loss=1334443.241936 | val_rmse=920.237064 | val_mae=264.358508 | val_r2=0.074269

2026-05-11 19:51:00,291 | INFO | Round 75/100 | train_loss=1331437.754678 | val_rmse=919.064256 | val_mae=263.821284 | val_r2=0.076628
2026-05-11 19:51:00,345 | INFO | Saved new best model at round 75 with val_rmse=919.064256

Round 75/100 | train_loss=1331437.754678 | val_rmse=919.064256 | val_mae=263.821284 | val_r2=0.076628

2026-05-11 19:51:54,631 | INFO | Round 76/100 | train_loss=1328429.120060 | val_rmse=917.886586 | val_mae=263.223721 | val_r2=0.078992
2026-05-11 19:51:54,691 | INFO | Saved new best model at round 76 with val_rmse=917.886586

Round 76/100 | train_loss=1328429.120060 | val_rmse=917.886586 | val_mae=263.223721 | val_r2=0.078992

2026-05-11 19:52:49,319 | INFO | Round 77/100 | train_loss=1325429.855736 | val_rmse=916.717077 | val_mae=262.673639 | val_r2=0.081338
2026-05-11 19:52:49,375 | INFO | Saved new best model at round 77 with val_rmse=916.717077

Round 77/100 | train_loss=1325429.855736 | val_rmse=916.717077 | val_mae=262.673639 | val_r2=0.081338

2026-05-11 19:53:43,541 | INFO | Round 78/100 | train_loss=1322435.500889 | val_rmse=915.537015 | val_mae=262.087034 | val_r2=0.083702
2026-05-11 19:53:43,609 | INFO | Saved new best model at round 78 with val_rmse=915.537015

Round 78/100 | train_loss=1322435.500889 | val_rmse=915.537015 | val_mae=262.087034 | val_r2=0.083702

2026-05-11 19:54:37,336 | INFO | Round 79/100 | train_loss=1319458.634205 | val_rmse=914.359142 | val_mae=261.517356 | val_r2=0.086058
2026-05-11 19:54:37,395 | INFO | Saved new best model at round 79 with val_rmse=914.359142

Round 79/100 | train_loss=1319458.634205 | val_rmse=914.359142 | val_mae=261.517356 | val_r2=0.086058

2026-05-11 19:55:31,717 | INFO | Round 80/100 | train_loss=1316479.717014 | val_rmse=913.220242 | val_mae=260.944405 | val_r2=0.088333
2026-05-11 19:55:31,797 | INFO | Saved new best model at round 80 with val_rmse=913.220242

Round 80/100 | train_loss=1316479.717014 | val_rmse=913.220242 | val_mae=260.944405 | val_r2=0.088333

2026-05-11 19:56:25,724 | INFO | Round 81/100 | train_loss=1313511.289911 | val_rmse=912.040940 | val_mae=260.399407 | val_r2=0.090686
2026-05-11 19:56:25,813 | INFO | Saved new best model at round 81 with val_rmse=912.040940

Round 81/100 | train_loss=1313511.289911 | val_rmse=912.040940 | val_mae=260.399407 | val_r2=0.090686

2026-05-11 19:57:20,307 | INFO | Round 82/100 | train_loss=1310545.305626 | val_rmse=910.878461 | val_mae=259.836543 | val_r2=0.093003
2026-05-11 19:57:20,372 | INFO | Saved new best model at round 82 with val_rmse=910.878461

Round 82/100 | train_loss=1310545.305626 | val_rmse=910.878461 | val_mae=259.836543 | val_r2=0.093003

2026-05-11 19:58:13,812 | INFO | Round 83/100 | train_loss=1307585.682275 | val_rmse=909.716685 | val_mae=259.250909 | val_r2=0.095315
2026-05-11 19:58:13,875 | INFO | Saved new best model at round 83 with val_rmse=909.716685

Round 83/100 | train_loss=1307585.682275 | val_rmse=909.716685 | val_mae=259.250909 | val_r2=0.095315

2026-05-11 19:59:06,653 | INFO | Round 84/100 | train_loss=1304634.593680 | val_rmse=908.572851 | val_mae=258.737724 | val_r2=0.097588
2026-05-11 19:59:06,713 | INFO | Saved new best model at round 84 with val_rmse=908.572851

Round 84/100 | train_loss=1304634.593680 | val_rmse=908.572851 | val_mae=258.737724 | val_r2=0.097588

2026-05-11 20:00:00,484 | INFO | Round 85/100 | train_loss=1301687.555371 | val_rmse=907.390644 | val_mae=258.173065 | val_r2=0.099935
2026-05-11 20:00:00,545 | INFO | Saved new best model at round 85 with val_rmse=907.390644

Round 85/100 | train_loss=1301687.555371 | val_rmse=907.390644 | val_mae=258.173065 | val_r2=0.099935

2026-05-11 20:00:54,235 | INFO | Round 86/100 | train_loss=1298751.527918 | val_rmse=906.249988 | val_mae=257.644055 | val_r2=0.102197
2026-05-11 20:00:54,292 | INFO | Saved new best model at round 86 with val_rmse=906.249988

Round 86/100 | train_loss=1298751.527918 | val_rmse=906.249988 | val_mae=257.644055 | val_r2=0.102197

2026-05-11 20:01:47,988 | INFO | Round 87/100 | train_loss=1295816.200557 | val_rmse=905.087813 | val_mae=257.044673 | val_r2=0.104498
2026-05-11 20:01:48,039 | INFO | Saved new best model at round 87 with val_rmse=905.087813

Round 87/100 | train_loss=1295816.200557 | val_rmse=905.087813 | val_mae=257.044673 | val_r2=0.104498

2026-05-11 20:02:40,981 | INFO | Round 88/100 | train_loss=1292895.830973 | val_rmse=903.919558 | val_mae=256.472932 | val_r2=0.106808
2026-05-11 20:02:41,037 | INFO | Saved new best model at round 88 with val_rmse=903.919558

Round 88/100 | train_loss=1292895.830973 | val_rmse=903.919558 | val_mae=256.472932 | val_r2=0.106808

2026-05-11 20:03:36,586 | INFO | Round 89/100 | train_loss=1289970.498787 | val_rmse=902.755442 | val_mae=255.930561 | val_r2=0.109107
2026-05-11 20:03:36,645 | INFO | Saved new best model at round 89 with val_rmse=902.755442

Round 89/100 | train_loss=1289970.498787 | val_rmse=902.755442 | val_mae=255.930561 | val_r2=0.109107

2026-05-11 20:04:32,025 | INFO | Round 90/100 | train_loss=1287063.071879 | val_rmse=901.593567 | val_mae=255.405085 | val_r2=0.111399
2026-05-11 20:04:32,094 | INFO | Saved new best model at round 90 with val_rmse=901.593567

Round 90/100 | train_loss=1287063.071879 | val_rmse=901.593567 | val_mae=255.405085 | val_r2=0.111399

2026-05-11 20:05:26,086 | INFO | Round 91/100 | train_loss=1284156.730608 | val_rmse=900.440168 | val_mae=254.828789 | val_r2=0.113671
2026-05-11 20:05:26,145 | INFO | Saved new best model at round 91 with val_rmse=900.440168

Round 91/100 | train_loss=1284156.730608 | val_rmse=900.440168 | val_mae=254.828789 | val_r2=0.113671

2026-05-11 20:06:20,862 | INFO | Round 92/100 | train_loss=1281251.944678 | val_rmse=899.279328 | val_mae=254.292752 | val_r2=0.115955
2026-05-11 20:06:20,926 | INFO | Saved new best model at round 92 with val_rmse=899.279328

Round 92/100 | train_loss=1281251.944678 | val_rmse=899.279328 | val_mae=254.292752 | val_r2=0.115955

2026-05-11 20:07:12,320 | INFO | Round 93/100 | train_loss=1278355.394029 | val_rmse=898.130204 | val_mae=253.715674 | val_r2=0.118213
2026-05-11 20:07:12,410 | INFO | Saved new best model at round 93 with val_rmse=898.130204

Round 93/100 | train_loss=1278355.394029 | val_rmse=898.130204 | val_mae=253.715674 | val_r2=0.118213

2026-05-11 20:08:07,094 | INFO | Round 94/100 | train_loss=1275470.113533 | val_rmse=896.975096 | val_mae=253.144288 | val_r2=0.120480
2026-05-11 20:08:07,179 | INFO | Saved new best model at round 94 with val_rmse=896.975096

Round 94/100 | train_loss=1275470.113533 | val_rmse=896.975096 | val_mae=253.144288 | val_r2=0.120480

2026-05-11 20:09:02,116 | INFO | Round 95/100 | train_loss=1272587.383548 | val_rmse=895.826364 | val_mae=252.649172 | val_r2=0.122731
2026-05-11 20:09:02,210 | INFO | Saved new best model at round 95 with val_rmse=895.826364

Round 95/100 | train_loss=1272587.383548 | val_rmse=895.826364 | val_mae=252.649172 | val_r2=0.122731

2026-05-11 20:09:56,497 | INFO | Round 96/100 | train_loss=1269720.346107 | val_rmse=894.674125 | val_mae=252.086046 | val_r2=0.124986
2026-05-11 20:09:56,562 | INFO | Saved new best model at round 96 with val_rmse=894.674125

Round 96/100 | train_loss=1269720.346107 | val_rmse=894.674125 | val_mae=252.086046 | val_r2=0.124986

2026-05-11 20:10:51,026 | INFO | Round 97/100 | train_loss=1266847.678151 | val_rmse=893.520169 | val_mae=251.547828 | val_r2=0.127242
2026-05-11 20:10:51,090 | INFO | Saved new best model at round 97 with val_rmse=893.520169

Round 97/100 | train_loss=1266847.678151 | val_rmse=893.520169 | val_mae=251.547828 | val_r2=0.127242

2026-05-11 20:11:45,717 | INFO | Round 98/100 | train_loss=1263986.805704 | val_rmse=892.387481 | val_mae=251.002218 | val_r2=0.129453
2026-05-11 20:11:45,779 | INFO | Saved new best model at round 98 with val_rmse=892.387481

Round 98/100 | train_loss=1263986.805704 | val_rmse=892.387481 | val_mae=251.002218 | val_r2=0.129453

2026-05-11 20:12:38,832 | INFO | Round 99/100 | train_loss=1261133.814675 | val_rmse=891.240313 | val_mae=250.477945 | val_r2=0.131690
2026-05-11 20:12:38,919 | INFO | Saved new best model at round 99 with val_rmse=891.240313

Round 99/100 | train_loss=1261133.814675 | val_rmse=891.240313 | val_mae=250.477945 | val_r2=0.131690

2026-05-11 20:13:32,748 | INFO | Round 100/100 | train_loss=1258287.610905 | val_rmse=890.094829 | val_mae=249.935214 | val_r2=0.133921
2026-05-11 20:13:32,822 | INFO | Saved new best model at round 100 with val_rmse=890.094829

Round 100/100 | train_loss=1258287.610905 | val_rmse=890.094829 | val_mae=249.935214 | val_r2=0.133921

,round,client_count,train_loss_mean,train_loss_weighted,val_loss,val_mae,val_rmse,val_smape,val_mape,val_r2,communication_upload_mb,communication_download_mb,communication_total_mb,communication_cumulative_mb
0,1,40,1.576759e+06,1.576758e+06,1.021611e+06,330.679216,1010.747532,NaN,NaN,-0.116787,11.660309,11.660309,23.320618,23.320618
1,2,40,1.570738e+06,1.570738e+06,1.018407e+06,327.461372,1009.161588,NaN,NaN,-0.113286,11.660309,11.660309,23.320618,46.641235
2,3,40,1.566895e+06,1.566895e+06,1.015666e+06,324.659396,1007.802786,NaN,NaN,-0.110290,11.660309,11.660309,23.320618,69.961853
3,4,40,1.563264e+06,1.563264e+06,1.012995e+06,322.699314,1006.476695,NaN,NaN,-0.107370,11.660309,11.660309,23.320618,93.282471
4,5,40,1.559659e+06,1.559659e+06,1.010319e+06,321.279371,1005.146205,NaN,NaN,-0.104444,11.660309,11.660309,23.320618,116.603088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,40,1.269721e+06,1.269720e+06,8.004418e+05,252.086046,894.674125,NaN,NaN,0.124986,11.660309,11.660309,23.320618,2238.779297
96,97,40,1.266848e+06,1.266848e+06,7.983783e+05,251.547828,893.520169,NaN,NaN,0.127242,11.660309,11.660309,23.320618,2262.099915
97,98,40,1.263987e+06,1.263987e+06,7.963554e+05,251.002218,892.387481,NaN,NaN,0.129453,11.660309,11.660309,23.320618,2285.420532
98,99,40,1.261134e+06,1.261134e+06,7.943092e+05,250.477945,891.240313,NaN,NaN,0.131690,11.660309,11.660309,23.320618,2308.741150
99,100,40,1.258288e+06,1.258288e+06,7.922688e+05,249.935214,890.094829,NaN,NaN,0.133921,11.660309,11.660309,23.320618,2332.061768

## 11. Final evaluation

Nakon treninga ucitavamo najbolji checkpoint i racunamo finalne metrike na spojenim train, val i test splitovima.

In [ ]:
best_state = torch.load(best_model_path, map_location=selected_device)
global_model.load_state_dict(best_state)

train_eval = evaluate_optional_split(
    model=global_model,
    split_arrays=global_train,
    batch_size=BATCH_SIZE,
    device=selected_device,
    loss_fn=loss_fn,
    method_name=method_name,
)
val_eval = evaluate_optional_split(
    model=global_model,
    split_arrays=global_val,
    batch_size=BATCH_SIZE,
    device=selected_device,
    loss_fn=loss_fn,
    method_name=method_name,
)
test_eval = evaluate_optional_split(
    model=global_model,
    split_arrays=global_test,
    batch_size=BATCH_SIZE,
    device=selected_device,
    loss_fn=loss_fn,
    method_name=method_name,
)

metrics_summary = pd.DataFrame(
    [
        {"split": "train", **train_eval["metrics"]},
        {"split": "val", **val_eval["metrics"]},
        {"split": "test", **test_eval["metrics"]},
    ]
)
metrics_summary.to_csv(run_dir / "metrics_summary.csv", index=False)

estimated_total_upload_bytes = model_state_bytes * len(train_clients) * NUM_ROUNDS
estimated_total_download_bytes = model_state_bytes * len(train_clients) * NUM_ROUNDS
estimated_total_communication_bytes = estimated_total_upload_bytes + estimated_total_download_bytes

final_metrics = {
    "run_name": RUN_NAME,
    "algorithm": ALGORITHM,
    "scenario": SCENARIO,
    "best_round": best_round,
    "best_val_rmse": best_val_rmse,
    "metrics": {
        "train": train_eval["metrics"],
        "val": val_eval["metrics"],
        "test": test_eval["metrics"],
    },
    "loss": {
        "train": train_eval["loss"],
        "val": val_eval["loss"],
        "test": test_eval["loss"],
    },
    "sample_counts": {
        "train": int(len(global_train.y)),
        "val": int(len(global_val.y)),
        "test": 0 if global_test is None else int(len(global_test.y)),
    },
    "communication": {
        "model_state_bytes": model_state_bytes,
        "model_state_mb": model_state_bytes / (1024 ** 2),
        "total_rounds": NUM_ROUNDS,
        "train_client_count": len(train_clients),
        "estimated_total_upload_mb": estimated_total_upload_bytes / (1024 ** 2),
        "estimated_total_download_mb": estimated_total_download_bytes / (1024 ** 2),
        "estimated_total_communication_mb": estimated_total_communication_bytes / (1024 ** 2),
    },
}
save_json(final_metrics, run_dir / "final_metrics.json")

metrics_summary

/tmp/ipykernel_4602/2308897797.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  best_state = torch.load(best_model_path, map_location=selected_device)

   split         rmse         mae        r2  sample_count
0  train  1163.484236  369.597768  0.019445        110642
1    val   928.356080  268.174098  0.057862          6824
2   test   938.662612  274.734128  0.053886         30275

## 12. Save predictions

Test predikcije spremamo s kolonama trazenima za usporedbu metoda.

In [ ]:
def prediction_frame_for_submission(evaluation_result: dict[str, Any], method: str) -> pd.DataFrame:
    frame = evaluation_result["prediction_frame"].copy()
    if frame.empty:
        return pd.DataFrame(columns=["t", "station_id", "y_true", "y_pred", "method"])
    frame["method"] = method
    return frame.loc[:, ["t", "station_id", "y_true", "y_pred", "method"]]


predictions_test = prediction_frame_for_submission(test_eval, method_name)
predictions_test.to_csv(run_dir / "predictions_test.csv", index=False)

predictions_test.head()

                               t station_id  y_true    y_pred           method
0  2023-01-15T17:00:00.000000000       1001     0.0  4.295914  fedavg_lstm_iid
1  2023-01-15T18:00:00.000000000       1001     0.0  0.099844  fedavg_lstm_iid
2  2023-01-15T19:00:00.000000000       1001     0.0  0.752899  fedavg_lstm_iid
3  2023-01-15T20:00:00.000000000       1001     0.0  2.398837  fedavg_lstm_iid
4  2023-01-15T21:00:00.000000000       1001     0.0  1.448497  fedavg_lstm_iid

## 13. Plots

Osnovni grafovi za konvergenciju i test predikcije. Koristi se samo matplotlib.

In [ ]:
def save_line_plot(df: pd.DataFrame, x_col: str, y_col: str, title: str, y_label: str, output_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.plot(df[x_col], df[y_col], marker="o", linewidth=1.8)
    ax.set_title(title)
    ax.set_xlabel(x_col)
    ax.set_ylabel(y_label)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    plt.close(fig)


save_line_plot(round_metrics, "round", "val_rmse", "Validation RMSE by round", "RMSE", plots_dir / "val_rmse_by_round.png")
save_line_plot(round_metrics, "round", "val_mae", "Validation MAE by round", "MAE", plots_dir / "val_mae_by_round.png")
save_line_plot(round_metrics, "round", "train_loss_weighted", "Weighted train loss by round", "MSE loss", plots_dir / "train_loss_by_round.png")

plot_frame = predictions_test.head(500).copy()
fig, ax = plt.subplots(figsize=(11, 4.8))
if not plot_frame.empty:
    ax.plot(plot_frame.index, plot_frame["y_true"], label="actual", linewidth=1.5)
    ax.plot(plot_frame.index, plot_frame["y_pred"], label="prediction", linewidth=1.5)
    ax.legend()
ax.set_title("Predictions vs actual - first 500 test samples")
ax.set_xlabel("sample")
ax.set_ylabel("target")
ax.grid(True, alpha=0.3)
fig.tight_layout()
fig.savefig(plots_dir / "predictions_vs_actual_first_500.png", dpi=150)
plt.close(fig)

pd.DataFrame(
    [
        {"plot": path.name, "path": str(path)}
        for path in sorted(plots_dir.glob("*.png"))
    ]
)

,plot,path
0,predictions_vs_actual_first_500.png,/mnt/batch/tasks/shared/LS_root/mounts/cluster...
1,train_loss_by_round.png,/mnt/batch/tasks/shared/LS_root/mounts/cluster...
2,val_mae_by_round.png,/mnt/batch/tasks/shared/LS_root/mounts/cluster...
3,val_rmse_by_round.png,/mnt/batch/tasks/shared/LS_root/mounts/cluster...

## 14. Output structure

Svi artefakti ovog runa nalaze se u `data/processed/results/federated/{RUN_NAME}/`.

In [ ]:
artifact_paths = [
    run_dir / "config.json",
    run_dir / "client_summary.csv",
    run_dir / "round_metrics.csv",
    run_dir / "best_model.pt",
    run_dir / "metrics_summary.csv",
    run_dir / "final_metrics.json",
    run_dir / "predictions_test.csv",
    plots_dir,
]

pd.DataFrame(
    [
        {"artifact": path.name, "path": str(path), "exists": path.exists()}
        for path in artifact_paths
    ]
)

,artifact,path,exists
0,config.json,/mnt/batch/tasks/shared/LS_root/mounts/cluster...,True
1,client_summary.csv,/mnt/batch/tasks/shared/LS_root/mounts/cluster...,True
2,round_metrics.csv,/mnt/batch/tasks/shared/LS_root/mounts/cluster...,True
3,best_model.pt,/mnt/batch/tasks/shared/LS_root/mounts/cluster...,True
4,metrics_summary.csv,/mnt/batch/tasks/shared/LS_root/mounts/cluster...,True
5,final_metrics.json,/mnt/batch/tasks/shared/LS_root/mounts/cluster...,True
6,predictions_test.csv,/mnt/batch/tasks/shared/LS_root/mounts/cluster...,True
7,plots,/mnt/batch/tasks/shared/LS_root/mounts/cluster...,True

## 15. Final summary

Kratki izvjestaj koji se moze direktno prepisati u biljeske eksperimenta.

In [ ]:
total_train_samples = int(len(global_train.y))
total_val_samples = int(len(global_val.y))
total_test_samples = 0 if global_test is None else int(len(global_test.y))

print(f"Ucitano klijenata: {len(all_clients)}")
print(f"Ukupno uzoraka | train={total_train_samples} val={total_val_samples} test={total_test_samples}")
print(f"Rezultati su spremljeni u: {run_dir}")

metrics_summary

Ucitano klijenata: 40
Ukupno uzoraka | train=110642 val=6824 test=30275
Rezultati su spremljeni u: /mnt/batch/tasks/shared/LS_root/mounts/clusters/lgjuric2/code/Users/lgjuric/federated-ev-charging-forecasting/data/processed/results/federated/notebook_fedavg_iid_20260511T164513Z

   split         rmse         mae        r2  sample_count
0  train  1163.484236  369.597768  0.019445        110642
1    val   928.356080  268.174098  0.057862          6824
2   test   938.662612  274.734128  0.053886         30275